### ISSUE TITLE
Space after new tag throws InvalidExpressionException

### ISSUE THREAD

**Issue by akaiSuicchi** [poppinss/edge#10]
**Version** 1.1.1
**Found** Bug

After reading the docs from both AdonisJS 4 and Edge (awesome projects btw) and write an example ...
```html
@if(username) 
  <h1> Hello {{ username }} </h1>
@else
  <h1> Hello anonymous </h1>
@endif
```
this happened
```console
{ InvalidExpressionException: E_INVALID_EXPRESSION: Invalid expression <username) > passed to (if) block
    at (C:\Users\prvjefolar0\Desktop\personal_workspace\test\views\whitespace.edge:1:0)
    at Function.invalidTagExpression (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Exceptions\index.js:87:19)
    at IfTag._compileStatement (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Tags\BaseTag.js:43:43)
    at IfTag.compile (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Tags\IfTag.js:82:36)
    at TemplateCompiler.parseTag (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Template\Compiler.js:152:21)
    at TemplateCompiler.parseLine (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Template\Compiler.js:186:12)
    at ast.forEach (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Template\Compiler.js:116:32)
    at Array.forEach (native)
    at TemplateCompiler._compileAst (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Template\Compiler.js:116:9)
    at TemplateCompiler.compile (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Template\Compiler.js:225:80)
    at Template._compileView (C:\Users\prvjefolar0\Desktop\personal_workspace\test\node_modules\edge.js\src\Template\index.js:221:37) lineno: 1, charno: '0' }
```
At first I wasn't sure about the problem. Then I copy/paste from docs and tried it again and everything was ok.
It turns out that I wrote the first line with a space
```html
@if(username)//space or &nbsp;
```
But only the first line, following tags (@else or @END_TAG ) take this without a problem.

Previous versions handle this except for 1.1.0.
Is not a big problem, if one write each line correctly this can be avoided but I thought I should report this.

PS. If this was already fixed in a future release please ignore this. 

Thanks for your time and effort on this projects.

**Comment by RomainLanz** [comment]
Hey @akaiSuicchi! 👋 

It should be fixed [ref](https://github.com/poppinss/edge/issues/3).
May you try to install `edge.js` from Github?

**Comment by akaiSuicchi** [comment]
Hi @RomainLanz .
You are right. After install ```edge.js``` from Github and run ```npm run test:win``` everything works just fine.
But then why version 1.1.0 and 1.1.1 fails from npm? I reinstall it and ```npm cache clear``` and still fails.

**Comment by RomainLanz** [comment]
This fix hasn't been released yet.
It'd be pretty soon 👌
